"""add contact_email to bookings

Revision ID: a1e1e384af3e
Revises: 367990a5840f
Create Date: 2026-03-05 11:07:40.418950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e1e384af3e'
down_revision: Union[str, Sequence[str], None] = '367990a5840f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
def upgrade() -> None:
    # 1) add column as nullable first
    op.add_column("bookings", sa.Column("contact_email", sa.String(), nullable=True))

    # 2) fill old rows using existing user email
    op.execute("""
        UPDATE bookings b
        SET contact_email = u.email
        FROM users u
        WHERE b.user_id = u.id
    """)

    # 3) make it NOT NULL
    op.alter_column("bookings", "contact_email", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'contact_email')
    # ### end Alembic commands ###
